spring:
  profiles.active: local
  application:
     name: portfolio
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

---
spring:
  profiles: local
  jpa:
     hibernate:
        ddl-auto: update
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    nonSecurePort: ${server.port}
---
spring:
  profiles: cloud
  jpa:
     hibernate:
        ddl-auto: update
eureka:
  instance:
    nonSecurePort: 80
---
logging:
  level:
     io:
        pivotal: INFO
     com:
        netflix: WARN
